---
title: "importanceSampling"
author: "Kwaku Peprah Adjei"
date: "2023-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Simulate data
```{r}
#Packages needed to run the model
library(nimble)
library(INLA)
library(mvtnorm)
library(MASS)
library(parallel)
library(coda)
library(ggmcmc)

# function for generating samples
set.seed(0)
sample.linreg <- function(){
  n = 100 # Number of samples
  x1 = runif(n) #covariate 1
  x2 = runif(n) #covariate 2
  err = rnorm(n) # error
  y = 2 + 3*x1 -3*x2 + err # Response
  return(list(y = y,x = as.matrix(cbind(x1, x2))))
}

#Data
bivariateSims <- sample.linreg()
```


#
```{r}
code <- nimble::nimbleCode({

  #Prior for beta1 and beta2
  for(i in 1:2){
    beta[i] ~ dnorm(0, tau = 0.01)
  }

  # Prior for intercept
  a ~ dunif(-1000, 1000)

# linear predictor
  for(i in 1:N){
  linpred[i] <-  a + beta[1]*x[i, 1] + beta[2]*x[i, 2]
  }

  #Bivariate linear model specification
  for(i in 1:N){
    y[i] ~ dnorm(linpred[i], tau= sigma)
  }

# Prior for precision parameter
  sigma ~ dgamma(1,0.00005)
})

# Parameterization
data = bivariateSims

#data
idm_data <- list(y=data$y,
                 x = data$x,
                 y_obs=data$y,
                 inter = 1)

# constants
constants = list(N = length(data$y),
                 mu = c(0,0),
                 precision_matrix = diag(5,2),
                 fam = "gaussian")

# Initial values
inits <-  function(){list(beta =c(0,0),
                          a = 1,
                          sigma = 1
)
}

initsList <- inits()

# INLA function
fit.inla <- function(x , # covariates (a matrix)
                     y , # a character showing which covariate is a vector
                     beta, # vars with MCMC
                     fixedVals, # vars with INLA
                     family # what is the parametric family
                     
){

  # set the data and the offset
  data <- list(y=y,
               x1=x[,1],
               x2 = x[,2])
  data$oset = beta[1]*data$x1 + beta[2]*data$x2
#try and check the offset
  formula = y ~  1 + offset(data$oset)
  # Fit INLA for Bayes average of the pars
  res = INLA::inla(formula,
                   data = data,
                   family = family,
                   verbose=FALSE,
                   control.fixed = list(prec.intercept = 0.001),
                   control.compute = list(config = TRUE),
                   control.predictor = list(compute = TRUE))

  # conditional marginal log-likelihood
  fitted_values = c(res$mlik[1,1])

  # estimate Bayesian averaging using inla.emarginal
  #intercept = INLA::inla.emarginal(function(x) x,res$marginals.fixed[[1]])
  #precision = INLA::inla.emarginal(function(x) x,res$marginals.hyper[[1]])

  #generate samples
  samples <- inla.posterior.sample(1, res)
  intercept = samples[[1]]$latent[grepl("Intercept",rownames(samples[[1]]$latent) ),1]
  precision <-  inla.hyperpar.sample(1, res)

  ret <- data.frame(mld = fitted_values,
                    intercept,
                    c(precision),
                    row.names = NULL)

  colnames(ret) <- c("mld", fixedVals)

  ret <- as.matrix(ret)
  return(ret)
}


fit.inlaPar <- function(x,
                        y,
                        betaMatrix,
                        fixedVals,
                        family,
                        nCores){
  runFnx <- function(i,
                     x,
                     y,
                     betaMatrix,
                     fixedVals,
                     family){
    res <- fit.inla(x=x,
                    y=y,
                    beta = betaMatrix[i, ],
                    fixedVals = fixedVals,
                    family=family)
    return(res)
  }
  
  m <- nrow(betaMatrix)
  allResults <- parallel::mclapply(1:m,
                                   runFnx,
                                   x,
                     y,
                     betaMatrix,
                     fixedVals,
                     family,
                     mc.cores = nCores)
  
  ret <- do.call("rbind", allResults)
  return(ret)
}

#test function
#betaMatrix <- matrix(c(1,-1,
 #            2, -2,
 #            1.5,-1.4), nrow =3, byrow = TRUE)

#fit.inlaPar(x=idm_data$x, y=idm_data$y, betaMatrix, fixedVals, "gaussian", nCores = 3)
# Set up the R function for use in INLA
nimbleINLA <- nimble::nimbleRcall(
  prototype = function(
    x=double(2), #x is a matrix
    y=double(1), #y is a vector
    beta=double(2), # beta is a vector
    fixedVals = character(1, default = c("a", "sigma")),
    family = character(0, default = "gaussian"),
    nCores = integer(0, default = 1)
  ) {},
  returnType = double(2), # outcome is a vector
  Rfun = 'fit.inlaPar'
)

#nimbleINLA(x=idm_data$x, y=idm_data$y, betaMatrix, fixedVals, "gaussian", nCores = 3)

    mwtc <- nimble::nimbleModel(code,
                                data = idm_data,
                                constants = constants,
                                inits = initsList)

    # Create the model in C
    Cmwtc <- nimble::compileNimble(mwtc,
                                   showCompilerOutput = FALSE) #Have issues compiling

```

# Importance sample algorithm






```{r}
covariate = data$x
x <- covariate
model <- mwtc
control = list(inlaModel = fit.inla,
                       fixedVals = c("a", "sigma"),
                      proposal = "dnorm",
                      initMean = c(0,0),
                      initCov = NULL,
                      timeIndex = 3)
y = "y"; target = "beta"
rr <- inlaIS(mwtc, "gaussian", x, y = "y", target = "beta",
       control = list(nimbleINLA = nimbleINLA,
                       fixedVals = c("a", "sigma"),
                      proposal = "normal",
                      initMean = c(0,0),
                      initCov = NULL,
                      timeIndex = 3,
                      nSteps = 3,
                      nCores = 2,
                      dfTdist = 3))

compileModel <- compileNimble(mwtc, rr)


out <- compileModel$rr$run(3)


#return results
compileModel$rr$mvEWSamples["beta"]
compileModel$rr$mvEWSamples["a"]
compileModel$rr$mvEWSamples["sigma"]
compileModel$rr$mvEWSamples["wts"]
```


```{r}
  data = c("y")
                        covariate = data$x
                        code = code
                        family = "gaussian"
                        modelData = idm_data
                        modelConstants = constants
                        modelInits = inits
                        nimbleINLA = nimbleINLA
                        inlaMCMC = "importanceSampling"
                        #inlaMCsampler = samplers[i]
                        samplerControl = list(scale = 0.75,
                                              #propCov = diag((1/0.75^2), 2),
                                              adaptive = FALSE,
                                              sliceMaxSteps = 30)
                        parametersToMonitor = list(mcmc = c("beta"),
                                                   inla = c("a", "sigma"))
                        mcmcConfiguration = list(n.chains = 3,
                                                 n.iterations = 12,
                                                 n.burnin = 5500,
                                                 n.thin = 3,
                                                 setSeed = TRUE,
                                                 samples=TRUE,
                                                 samplesAsCodaMCMC = TRUE,
                                                 summary = TRUE,
                                                 WAIC = FALSE)
                        
```


```{r}
INLAWiNimDataGenerating <- function(data,
                                    covariate,
                                    code,
                                    family,
                                    modelData,
                                    modelConstants,
                                    modelInits,
                                    nimbleINLA,
                                    inlaMCMC = c("inla", "mcmc", "inlamcmc"),
                                    inlaMCsampler = "RW_INLA_block",
                                    samplerControl = list(proposal = "normal",
                                                          initMean = NULL,
                                                          initCov = NULL,
                                                          nCores = 2),
                                    parametersToMonitor = list(mcmc = c("mcmc"),
                                                               inla = c("inla"),
                                                               additionalPars = NULL),
                                    mcmcConfiguration = list(n.chains = 1,
                                                             n.iterations = 10,
                                                             n.burnin = 0,
                                                             n.thin = 1,
                                                             setSeed = TRUE,
                                                             samples=TRUE,
                                                             samplesAsCodaMCMC = TRUE,
                                                             summary = TRUE,
                                                             WAIC = FALSE)){



  #extract necessary variables
  x <- covariate # must be a matrix
  y <- data # must be a vector
  family <- family
  fixedVals <- parametersToMonitor$inla
  target <- parametersToMonitor$mcmc

  #set up initial value
  initsList <- modelInits()

  #Create the model in nimble
  mwtc <- nimble::nimbleModel(code,
                              data = modelData,
                              constants = modelConstants,
                              inits = initsList)

  # Create the model in C
  Cmwtc <- nimble::compileNimble(mwtc,
                                 showCompilerOutput = FALSE) #Have issues compiling

  #create list to return
  retList <- list()
  # Fit INLAMCMC

  if(inlaMCMC %in% "inlamcmc"){
    mcmcconf <- nimble::configureMCMC(Cmwtc,
                                      nodes = NULL)

    # setting sampler controls
    samplerControl$fit.inla = nimbleINLA
    samplerControl$x = x
    samplerControl$y = y
    samplerControl$fixedVals = fixedVals
    samplerControl$fam = family

    # mcmc configuration
    mcmcconf$addSampler(target = target,
                        type = inlaMCsampler,
                        control = samplerControl)

    mcmcconf$printSamplers(executionOrder = TRUE)
    mcmcconf$addMonitors(target)

    if(!is.null(parametersToMonitor$additionalPars)){
      mcmcconf$addMonitors(parametersToMonitor$additionalPars)
    }

    #build model
    Rmcmc <- nimble::buildMCMC(mcmcconf)

    # Compile
    cmcmc <- nimble::compileNimble(Rmcmc,
                                   project = Cmwtc,
                                   resetFunctions = TRUE)
    startTime <- Sys.time()
    mcmc.out <- nimble::runMCMC(cmcmc,
                                niter = mcmcConfiguration[["n.iterations"]],
                                nchains = mcmcConfiguration[["n.chains"]],
                                nburnin = mcmcConfiguration[["n.burnin"]],
                                #inits = initsList,
                                thin = mcmcConfiguration[["n.thin"]],
                                setSeed = mcmcConfiguration[["setSeed"]],
                                samples = mcmcConfiguration[["samples"]],
                                samplesAsCodaMCMC = mcmcConfiguration[["samplesAsCodaMCMC"]],
                                summary = mcmcConfiguration[["summary"]],
                                WAIC = mcmcConfiguration[["WAIC"]])
    endTime <- Sys.time()
    timeTaken <- difftime(endTime, startTime, units = "secs")
      #as.numeric(endTime - startTime)

    ret <- list(mcmc.out = mcmc.out,
                timeTaken = timeTaken)

    #save inlamcmc results
    retList$inlamcmc <- ret
  }

  if(inlaMCMC %in% "mcmc"){
    mcmcconf <- nimble::configureMCMC(Cmwtc,
                                      monitors = c(target, fixedVals))


    mcmcconf$printSamplers()

    # Add new samplers
    mcmcconf$removeSampler(target)
   # mcmcconf$removeSampler("beta")
    #mcmcconf$addSampler("beta", type = inlaMCsampler)
    mcmcconf$addSampler(target, type = inlaMCsampler,
                        control = samplerControl)

    mcmcconf$printSamplers(executionOrder = TRUE)

    if(!is.null(parametersToMonitor$additionalPars)){
      mcmcconf$addMonitors(parametersToMonitor$additionalPars)
    }
    #build model
    Rmcmc <- nimble::buildMCMC(mcmcconf, useConjugacy = FALSE)

    # Compile
    cmcmc <- nimble::compileNimble(Rmcmc,
                                   project = Cmwtc,
                                   resetFunctions = TRUE)
    startTime <- Sys.time()
    mcmc.out <- nimble::runMCMC(cmcmc,
                                niter = mcmcConfiguration[["n.iterations"]],
                                nchains = mcmcConfiguration[["n.chains"]],
                                nburnin = mcmcConfiguration[["n.burnin"]],
                                #inits = initsList,
                                thin = mcmcConfiguration[["n.thin"]],
                                setSeed = mcmcConfiguration[["setSeed"]],
                                samples = mcmcConfiguration[["samples"]],
                                samplesAsCodaMCMC = mcmcConfiguration[["samplesAsCodaMCMC"]],
                                summary = mcmcConfiguration[["summary"]],
                                WAIC = mcmcConfiguration[["WAIC"]])
    endTime <- Sys.time()
    timeTaken <- difftime(endTime, startTime, units = "secs")

    ret <- list(mcmc.out = mcmc.out,
                timeTaken = timeTaken)

    #save results for MCMC
    retList$mcmc <-  ret
  }
  
  if(inlaMCMC %in%"importanceSampling"){
    samplerControl$nimbleINLA <- nimbleINLA
    samplerControl$family <- family
    samplerControl$fixedVals <- fixedVals
    samplerControl$timeIndex <- ceiling(mcmcConfiguration[["n.iterations"]]/(mcmcConfiguration[["n.chains"]]))
    samplerControl$nSteps <- mcmcConfiguration[["n.chains"]]
    rr <- inlaIS(mwtc, 
                 family, 
                 x, 
                 y, 
                 target,
       control = samplerControl)

    #compile Model
    compileModel <- compileNimble(mwtc, rr)

 startTime <- Sys.time()
out <- compileModel$rr$run()
endTime <- Sys.time()
timeTaken <- difftime(endTime, startTime, units = "secs")
    
mcmc.matrix <- as.matrix(compileModel$rr$mvEWSamples)

indices <- lapply(as.list(c("gamma", "wts")), function(x){
  ret <- startsWith(colnames(mcmc.matrix), x)
  ret <- which(ret == TRUE)
  return(ret)
})%>%
  do.call("c", .)

nburnin = mcmcConfiguration[["n.burnin"]]
res <- mcmc.matrix[-(1:nburnin), -indices]

  #as samplesAsCodaMCMC
  samplesList1 <- coda::as.mcmc.list(coda::as.mcmc(res))
  
  #save samples and summary
  mcmc.out <- list()
    #Estimating summary
  summaryObject <- lapply(samplesList1, samplesSummary)
  names(summaryObject) <- paste0('chain', 1)
  summaryObject$all.chains <- samplesSummary(do.call('rbind', samplesList1))
mcmc.out$samples <- samplesList1
mcmc.out$summary <- summaryObject

    ret <- list(mcmc.out = mcmc.out,
                timeTaken = timeTaken,
                ess = out)

    #save inlamcmc results
    retList$isINLA <- ret

#colnames(mcmc.matrix)%in%grepl(target, colnames(mcmc.matrix))
#[, mwtc$expandNodeNames(nodes = c(target, fixedVals))]
    #run function
   # out <- 
  }
  return(retList)
}
```

**test function**
```{r}

  inlaNimBivariate <- INLAWiNimDataGenerating(data = c("y"),
                        covariate = bivariateSims$x,
                        code = code,
                        family = "gaussian",
                        modelData = idm_data,
                        modelConstants = constants,
                        modelInits = inits,
                        nimbleINLA = nimbleINLA,
                        inlaMCMC = "importanceSampling",
                        inlaMCsampler = samplers[i],
                        samplerControl = list(scale = 0.75,
                                              #propCov = diag((1/0.75^2), 2),
                                              adaptive = FALSE,
                                              sliceMaxSteps = 30,
                                              initMean = c(1,-1),
                                              initCov= 5*diag(2),
                                              proposal = "normal",
                                              nCores = 4),
                        parametersToMonitor = list(mcmc = c("beta"),
                                                   inla = c("a", "sigma")),
                        mcmcConfiguration = list(n.chains = 10,
                                                 n.iterations = 200,
                                                 n.burnin = 50,
                                                 n.thin = 3,
                                                 setSeed = TRUE,
                                                 samples=TRUE,
                                                 samplesAsCodaMCMC = TRUE,
                                                 summary = TRUE,
                                                 WAIC = FALSE)
                        )
```

