---
title: "INLA_Within_Nimble"
author: "Kwaku Peprah Adjei"
date: '2022-10-27'
output: pdf_document
---

```{r setup, include=FALSE}
library(myphdthesis)
```


#Bivariate regression
```{r, message=FALSE, warning=FALSE, include=FALSEl}
# Bivariate regression

data("data_for_simulations")

# Nimble code
code <- nimble::nimbleCode({
  #Prior for beta1 and beta2
  #beta[1:2] ~ dmnorm(mu[1:2], cov=precision_matrix[1:2,1:2])
  for(i in 1:2){
    beta[i] ~ dnorm(0, tau = 0.01)
  }

  #Fitting the inla with the simulated parameters
  inla.res[1:N, 1:3] <- nimbleINLA(x[1:N,1:2],y_obs[1:N],beta[1:2],inter)

  sigma <- inla.res[1,2]
  linpred[1:N] <-  inla.res[1:N, 1]

  #Bivariate linear model specification
  for(i in 1:N){
    y[i] ~ dnorm(linpred[i], tau=sigma)
  }

  tau <- sigma
  intercept <- inla.res[1,1]
})


data = df
idm_data <- list(y=data$y,
                 x = data$x,
                 y_obs=data$y,
                 inter = 1)

constants = list(N = length(data$y),
                 mu = c(0,0),
                 precision_matrix = diag(5,2),
                 fam = "gaussian")

inits <-  function(){list(beta =c(1,1)
)
}

# Fit the INLA within Nimble model
inlaNimBivariate = INLAWiNim (data = df, code = code,
                     modelData = idm_data,
                     modelConstants = constants,
                     modelInits = inits,
                     fam = "gaussian",
                     mcmcConfiguration =  list(n.chains = 1,
                                               n.iterations = 1000,
                                               n.burnin = 200,
                                               n.thin = 1,
                                               setSeed = TRUE,
                                               samples=TRUE,
                                               samplesAsCodaMCMC = TRUE,
                                               summary = TRUE,
                                               WAIC = FALSE))
save(inlaNimBivariate, file = "BayesianRegression.RData")

```


### Plot results
```{r}
#Plot results
load("BayesianRegression.RData")
ggSamples <- ggmcmc::ggs(inlaNimBivariate$mcmc.out$samples)
ggmcmc::ggs_pairs(ggSamples, lower = list(continuous = "density"))
```


# Bayesian laso
```{r, message=FALSE, warning=FALSE, include=FALSE}
#bayesian Lasso
data("hitters_data")
code <- nimbleCode({

  alpha ~ dnorm(0,1)


  for(j in 1:P){
    beta[j] ~ ddexp(location = 0, rate=est_lam)
  }
  #Fitting the inla with the simulated parameters
  inla.res[1:N, 1:3] <- nimbleINLA(x[1:N,1:P],y_obs[1:N],beta[1:P], interInModel)

  #linpred[1:N] <- inla.res[1:100,3]
  sigma <- inla.res[1,2]
  linpred[1:N] <-  inla.res[1:N, 3] + alpha

  intercept <- inla.res[1,2]

  # linear model specification
  for(i in 1:N){
    y[i] ~ dnorm(linpred[i], tau=sigma)
  }

  # tau <- sigma
  #intercept <- inla.res[1,1]
})

inla_data <- list(y=as.numeric(df$y),
                  x = df$x,
                  y_obs=as.numeric(df$y),
                  interInModel = 2)

#Constants
const <- list(N = length(df$y),
              P= ncol(df$x),
              est_lam = 1/0.073
)

# Initial values
idm_inits <- function(){list(alpha = 0,
                             beta=rep(0,const$P)
)
}

inlaNimLasso = INLAWiNim (data = df, code = code,
                     modelData = inla_data,
                     modelConstants = const,
                     modelInits = idm_inits,
                     fam = "gaussian",
                     parametersToMonitor = c("beta", "alpha","sigma"),
                     mcmcConfiguration =  list(n.chains = 1,
                                               n.iterations = 1000,
                                               n.burnin = 200,
                                               n.thin = 1,
                                               setSeed = TRUE,
                                               samples=TRUE,
                                               samplesAsCodaMCMC = TRUE,
                                               summary = TRUE,
                                               WAIC = FALSE))

save(inlaNimLasso, file = "BayesianLassoResults.RData")

```

### Plot results
```{r}
load("BayesianLassoResults.RData")
ggSamples <- ggmcmc::ggs(inlaNimLasso$mcmc.out$samples)
ggmcmc::ggs_density(ggSamples)+
  ggplot2::facet_wrap(~Parameter, ncol = 3)
```


# Missing covariates
```{r,message=FALSE, warning=FALSE, include=FALSE}

# Missing covariates
library(mice)
data(nhanes2)

# data
d.mis <- nhanes2
idx.mis <- which(is.na(d.mis$bmi)) # finding na's
n.mis <- length(idx.mis) # number of nans
d.mis = cbind(age = as.numeric(d.mis$age),
              bmi = d.mis$bmi,
              chl = d.mis$chl)
df = list(d.mis = d.mis, idx.mis = idx.mis)


code <- nimbleCode({

 eta[1: n.idx] ~ dmnorm(muMiss[1:n.idx], cov = covMiss[1:n.idx, 1:n.idx])

  #Fitting the inla with the simulated parameters
  inla.res[1:N, 1:5] <- nimbleINLAMissingValues(x[1:N,1:3], idxMiss[1:n.idx], eta[1: n.idx])

  sigma <- inla.res[1,2]
  linpred[1:N] <-  inla.res[1:N, 5]


  # linear model specification
  for(i in 1:N){
    y[i] ~ dnorm(linpred[i], tau=sigma)
  }

})

inla_data <- list(y = as.numeric(df$d.mis[,3]),
                  x = df$d.mis,
                  idxMiss = df$idx.mis
                  )

#Constants
const <- list(N = nrow(df$d.mis),
              n.idx = length(df$idx.mis),
              muMiss = rep(mean(df$d.mis[,2], na.rm = T), length(df$idx.mis)),
              covMiss = diag(mean(df$d.mis[,2], na.rm = T), length(df$idx.mis))


)

# Initial values
idm_inits <- function(){list(eta = rep(0, const$n.idx)
)
}

inlaNimMissing = INLAWiNim (data = df, code = code,
                     modelData = inla_data,
                     modelConstants = const,
                     modelInits = idm_inits,
                     fam = "gaussian",
                     parametersToMonitor = c("eta"),
                     mcmcConfiguration =  list(n.chains = 1,
                                               n.iterations = 1000,
                                               n.burnin = 200,
                                               n.thin = 1,
                                               setSeed = TRUE,
                                               samples=TRUE,
                                               samplesAsCodaMCMC = TRUE,
                                               summary = TRUE,
                                               WAIC = FALSE))

save(inlaNimMissing, file = "missingCovariates.RData")
```

```{r,message=FALSE, warning=FALSE}
load( "missingCovariates.RData")
ggSamples <- ggmcmc::ggs(inlanim$mcmc.out$samples)
ggmcmc::ggs_density(ggSamples)+
  ggplot2::facet_wrap(~Parameter, ncol = 3)
```

